### ISSUE TITLE
can't generate the payload

### ISSUE THREAD

**Issue by nhsh** [4w4k3/Insanity-Framework#1]
after installing it with the prerequisites
and choosing the payload with the LHOST and LPORT 
I get this message 

`wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "dammed.py", line 439, in <module>
    main()
  File "dammed.py", line 421, in main
    asker() 
  File "dammed.py", line 192, in asker
    os.rename('dist/new.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory
`

any thoughts ?

**Comment by 4w4k3** [comment]
Type "wine pywin32-220.win32-py2.7.exe" i've write win32-220.win32-py2.7.exe. Now Its OK

or delete and clone it again

**Comment by 4w4k3** [comment]
For manually installation of prerequisites, use:
sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine
wget https://www.python.org/ftp/python/2.7.13/python-2.7.13.msi
wine msiexec /i python-2.7.13.msi /L*v log.txt
wget https://ufpr.dl.sourceforge.net/project/pywin32/pywin32/Build%20220/pywin32-220.win32-py2.7.exe
sudo wine win32-220.win32-py2.7.exe
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip install pyinstaller
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip uninstall Crypto
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip uninstall pycrypto
wget https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi
sudo wine msiexec /i VCForPython27.msi /L*v log2.txt
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip install pycrypto
mkdir .OK
