### ISSUE TITLE
Create a configuration for Insanity

### ISSUE THREAD

**Issue by Ekultek** [4w4k3/Insanity-Framework#10]
Referencing #7 

I'm going to take an educated guess and assume that what is happening is that the users aren't running `enc.py` first and are trying to create payloads, so what I'm suggesting is writing a configuration for Insanity that will create all needed files, extensions, etc the first time it is run that way everything is already in play and ready for the user to begin. What do you think?

**Comment by 4w4k3** [comment]
I understand you and this should be made.

**Comment by Ekultek** [comment]
Cool, I'll start working on it later today, unless you want to?

**Comment by Ekultek** [comment]
I'll also be adding a requirements.txt file for installing required libraries

**Comment by 4w4k3** [comment]
By me fine. :)
