### ISSUE TITLE
Pycrypto in multiple places

### ISSUE THREAD

**Issue by Ekultek** [4w4k3/Insanity-Framework#15]
The point of the `requirements.txt` file is to install the dependent libraries that are needed for python itself, to run this file you `pip install -r requirements.txt` which will install `pycrypto`. Your latest push `fix missing pycrypto` is unnecessary, and adds a double install when the requirements are already satisfied. I suggest that you remove either the requirements.txt file, or you remove the `#os.system()` install of `pycrypto`

**Comment by 4w4k3** [comment]
@Ekultek pycrypto is necessary on time to compile 'cause if he don't present compiler will fails. And when i speak about 'compile', are telling about pyinstaller on Wine Machine, not on main system.

**Comment by Ekultek** [comment]
@4w4k3 I think we're having a miscommunication, pip will compile the library as it should be compiled, that's the point of pip is to install libraries. Have you tried installing pycrypto from pip? Running `pip install -r requirements.txt` will install everything listed in the requirements.txt file and compile the libraries as needed

**Comment by 4w4k3** [comment]
@Ekultek  pip works but it in main system, we need pycrypto on python 2.7 of wine windows 7

**Comment by Ekultek** [comment]
https://pypi.python.org/pypi/pycrypto there's only one .whl for pycrypto, so no matter how it's installed it works for all version 2.6 +

**Comment by 4w4k3** [comment]
Yeah, but the payloads are compiled through wine and need pycrypto in wine not on linux

**Comment by Ekultek** [comment]
gotcha, alright
