### ISSUE TITLE
File Transfer

### ISSUE THREAD

**Issue by 4w4k3** [4w4k3/Insanity-Framework#16]
I need help with this function.

**Comment by Ekultek** [comment]
What are you trying to do exactly?

- Thomas Perkins

**Comment by 4w4k3** [comment]
Download and upload files from host to target.

**Comment by Ekultek** [comment]
I'll see what I can do in the morning, man.

- Thomas Perkins

**Comment by Ekultek** [comment]
So I did some research, this is gonna be a tough one. From the looks of it, we're going to need a client and a server, some how we're gonna have to make the target forcibly connect to the server platform and send through the server using TCP and sockets. I think we should coordinate and figure out a way we can code together in real time, so we have a way to see what's going on

**Comment by 4w4k3** [comment]
Yeah, insanity already use client and server, we need make a file transfer only, you can see client code in templates and server in striker.
