### ISSUE TITLE
python2.7: can't open file 'dammed.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by omriman067** [4w4k3/Insanity-Framework#6]
hey, i keep getting the message:
python2.7: can't open file 'dammed.py': [Errno 2] No such file or directory
when I try to create a payload. do you know whats wrong?
i'm running on ubuntu on amazon ec2.
thank you very much :)

**Comment by 4w4k3** [comment]
Do You have cloned it?
If yes please try manually:
in insanity's directory on shell type:
python2.7 dammed.py

Note:  to all features work, is necessary to clone.
You can do this with:
git clone https://github.com/4w4k3/Insanity-Framework
